### ISSUE TITLE
Remove dependence on scala.io

### ISSUE THREAD

**Issue by szeiger** [pathikrit/better-files#105]
Just a quick heads-up: We discussed further modularization and deprecation of the Scala library at the Scala team meeting last week. One candidate for deprecation and removal is the `scala.io` package. Better Files currently relies on `scala.io.Codec` so it would be good if this could be changed in order for Better Files to become part of the Scala Platform.

This straight-forward option would be to copy `scala.io.Codec` into Better Files.

(My personal opinion is that relying on an *implicit* codec is a bad idea in general and should be changed. Java does not properly distinguish between file encodings and console encodings and it is common nowadays to rely on UTF-8 for files, no matter what the legacy platform encoding says, so one *always* has to consider which encoding to use.)

**Comment by pathikrit** [comment]
I can depend instead on `java.nio.Charset`?
