### ISSUE TITLE
symbolicLink method yields an absolute path even if the target is a relative path

### ISSUE THREAD

**Issue by Horneth** [pathikrit/better-files#115]
The `symbolicLink` method calls `java.nio.Files.readSymbolicLink` which will return the target of the link. If the target is relative it will return a relative path. However the `symbolicLink` method will implicitly convert the `java.nio.Path` to a `better.File`, and in doing so will call `toAbsolutePath`, which will create an absolute path using the current directory. This is not the intended behavior for a relative symlink target which should be relative to its source, not the current directory.

e.g:

```
$ tree foo
foo
├── bar
└── baz -> bar
```

If I have a `better.File` for baz, and call `symbolicLink` on it, I should get a relative path "bar", and not an absolute path `$(pwd)/bar`

Would it be possible / preferable to have the `symbolicLink` method explicitly create a `better.File` without calling `toAbsolutePath` on the target path ?

**Comment by jvican** [comment]
@Horneth Would you mind having a look at a potential solution? This looks like an easy issue to fix. Let us know if you need anything on our side.

**Comment by Horneth** [comment]
@jvican Here's a small PR to try and fix this https://github.com/pathikrit/better-files/pull/125
