### ISSUE TITLE
Scala Platform Release

### ISSUE THREAD

**Issue by pathikrit** [pathikrit/better-files#122]
@jvican mentioned here (https://github.com/pathikrit/better-files/issues/121#issuecomment-284876613) that Scala Platform is planning a release of better-files. I also have a bigger v4 release planned. See: https://github.com/pathikrit/better-files/blob/master/CHANGES.md

Is there something we should collaborate on? What else needs to be done for a Scala Platform release

**Comment by jvican** [comment]
Hey Pathikrit, yeah, I'm planning to cut a release either this week or next one. As better-files is in the incubation period, I think we can already benefit from it and let people try it out.
  
I'm also planning to give the accepted modules a lot of exposure in hackathons, I'd like people to hack on them. I'll keep you posted on this one. I think that we can actually cut v3 release as a Scala Platform module release.
  
Have you thought about a better name? What about `Scala NIO`? The namespace could be `org.scala-lang.platform.nio`.

**Comment by jvican** [comment]
I'm sorry for my delay on this, I'm finishing up the last bits to integrate better-files with the Scala Platform CI and the releases. I'm submitting a PR soon.

**Comment by pathikrit** [comment]
@jvican : I created a PR to add back support for 2.11: https://github.com/pathikrit/better-files/pull/147/files

What else needs to be done for Scala Platform release?

**Comment by jvican** [comment]
Thank you @pathikrit. I'm working on integrating sbt-platform with https://github.com/scalacenter/sbt-release-early. As soon as I'm done, I'll PR it and done :smile:.

**Comment by jvican** [comment]
Cross-linking to a status update: https://github.com/mdedetrich/scala-json-ast/issues/12#issuecomment-297357236.

**Comment by jarrodwb** [comment]
https://contributors.scala-lang.org/t/spp-november-meeting-minutes/1404

It looks like you did it!
Cant this issue be closed?

**Comment by pathikrit** [comment]
Yes I think I needed to upgrade to SBT 1.0 and also support Scala 2.11, 2.12 and 2.13 (TBD). Looks like we can close this issue for now unless @jvican has something else in mind?
