### ISSUE TITLE
cannot resolve File.resource and File.usingTemporaryFile but can resolve File.newTemporaryFile

### ISSUE THREAD

**Issue by GreatTreeInField** [pathikrit/better-files#124]
With better.files.File object, 
some methods like File.newTemporaryFiles can be resolved, 
but some methods like File.usingTemporaryFile cannot be resolved  in my intellij.
I tried it with some version's better-files (2.17.1, 2.16.0, 2.15.0,2.14.0) 
and with sbt and maven. but in the same result.
I also tried clearing cache of IDE.
I'm using scala-2.11.8.

Do you know how to fix it or is it a bug?

**Comment by GreatTreeInField** [comment]
Sorry, I solved the issue by myself.
Just update intellij and scala plugin.

**Comment by pathikrit** [comment]
Its in the v3 release which has not been released yet. See #122

**Comment by GreatTreeInField** [comment]
thanks a lot
