### ISSUE TITLE
zip API implementation issues 

### ISSUE THREAD

**Issue by arpansoni** [pathikrit/better-files#128]
I am not able to find the correct implementation for  unzipto() function 
 in the example below how i am not able to figure out proper path 
 
val research: File = zipFile.unzipTo(destination = home/"data"/"adr"/"dev"/"ybextracted"/)

what is "home" here? 

also when i run the code on cluster  i am getting  file not found error   
                val zipFile: File = file"/data/adr/dev/YieldCurves_BD1.zip"
on my local this  command works.

Any example of complete implementation is appreciated.

Thanks,

**Comment by pathikrit** [comment]
home is the user's home directory. See: http://stackoverflow.com/questions/585534/what-is-the-best-way-to-find-the-users-home-directory-in-java

Why are you unzipping to your home directory? You should try just unzipping without a destination param - it would unzip to your temp directory and return that.

And what do you mean by cluster? A spark cluster? My guess is that your zip file lives in the master of your cluster and is not available in the other nodes of the cluster.
