### ISSUE TITLE
Use scalafmt

### ISSUE THREAD

**Issue by pathikrit** [pathikrit/better-files#133]

**Comment by jiminhsieh** [comment]
Can I work on this one? But there is a question about scalafmt configuration. Which style do you prefer to use?  Or maybe we could use default configuration in the beginning.

**Comment by pathikrit** [comment]
Yes, please work on this one - let's start with the default one so far. I currently like the style I have so minimal changes to the code is preferred.

**Comment by jiminhsieh** [comment]
Do you prefer [`sbt-scalafmt`](http://scalameta.org/scalafmt/#sbt-scalafmt) or [`neo-sbt-scalafmt`](http://scalameta.org/scalafmt/#neo-sbt-scalafmt)? It seems `neo-sbt-scalafmt` is more configurable, but `sbt-scalafmt` is sufficient to do the work.

**Comment by pathikrit** [comment]
Use whichever has higher likelihood being maintained few years from now ... Else, the least powerful one that does the job :)
