### ISSUE TITLE
Version 3.0.0 for Scala 2.11

### ISSUE THREAD

**Issue by lu4nm3** [pathikrit/better-files#146]
Is there any chance that you'll release version 3.0.0 for Scala 2.11?

**Comment by pathikrit** [comment]
You can safely use `2.17.x` across 2.10, 2.11 and 2.12. 3.0.0 onwards only 2.12+ is supported.

**Comment by pathikrit** [comment]
I just released v3.3.1 for Scala 2.11 and up
