### ISSUE TITLE
 not found: type FileMonitor [error]  

### ISSUE THREAD

**Issue by fangqiao** [pathikrit/better-files#151]
Hi, I am trying your lib following your sample code:

      val watcher = new FileMonitor(path, recursive = false) 

Imports are: 

import better.files.{File => ScalaFile, _}
import java.io.File

SBT decencie is :

    "com.github.pathikrit" % "better-files_2.12" % "3.0.0"

I got this compiling error:

not found: type FileMonitor
[error]       val watcher = new FileMonitor(path, recursive = false) {

...

Did I miss anything?
I use scala 2.12.2

**Comment by pathikrit** [comment]
The `FileMonitor` was introduced in 3.1 (not released yet). 
Try `ThreadBackedFileMonitor`. Docs are here for v3.0.0
https://github.com/pathikrit/better-files/tree/eb7a357713c083534de9eeaee771750582c8ad31
