### ISSUE TITLE
[Feature Request] Faster File Equals via Adler32?

### ISSUE THREAD

**Issue by Daxten** [pathikrit/better-files#163]
Hey,
what do you guys think of using adler32 for file equalization?
Maybe a bit like rsync does it:

- Check equal files length
- Don't make 1 hash of the hole file, but for example create 3 chunks and hash those

should be way faster and equal/better in safety I think?

Maybe even add a quick check which only checks metadata?

**Comment by pathikrit** [comment]
That's exactly what it does now. I have an issue open to also do check otherwise. See: https://github.com/pathikrit/better-files/issues/22
