### ISSUE TITLE
test failure in GlobSpec

### ISSUE THREAD

**Issue by SethTisue** [pathikrit/better-files#165]
found when attempting to add better-files to the Scala 2.12 community build

also reproducible for me outside the community build just by cloning the repo and doing `core/testOnly *GlobSpec`

```
[info] - should match all txt-files  under sub-directory (e.g. '.*/.*\\.txt') *** FAILED ***
[info]   Result: SIZE: 0
[info]   
[info]   Reference: SIZE: 8
[info]   PATH: /var/folders/h7/qlkb647s6dz25j170cq240tw0000gn/T/glob-tests7494021232790431127/globtree/a/a.txt
[info]   PATH: /var/folders/h7/qlkb647s6dz25j170cq240tw0000gn/T/glob-tests7494021232790431127/globtree/a/a2/a2.txt
[info]   PATH: /var/folders/h7/qlkb647s6dz25j170cq240tw0000gn/T/glob-tests7494021232790431127/globtree/a/a2/x.txt
[info]   PATH: /var/folders/h7/qlkb647s6dz25j170cq240tw0000gn/T/glob-tests7494021232790431127/globtree/a/x.txt
[info]   PATH: /var/folders/h7/qlkb647s6dz25j170cq240tw0000gn/T/glob-tests7494021232790431127/globtree/b/a/ba.txt
[info]   PATH: /var/folders/h7/qlkb647s6dz25j170cq240tw0000gn/T/glob-tests7494021232790431127/globtree/b/b.txt
[info]   PATH: /var/folders/h7/qlkb647s6dz25j170cq240tw0000gn/T/glob-tests7494021232790431127/globtree/c/c.txt
[info]   PATH: /var/folders/h7/qlkb647s6dz25j170cq240tw0000gn/T/glob-tests7494021232790431127/globtree/c/x.txt
[info]   0 did not equal 8 (GlobSpec.scala:133)
[info] - should use parent dir for matching (e.g. plain 'subdir/*.ext' instead of '**/subdir/*.ext) *** FAILED ***
[info]   Result: SIZE: 0
[info]   
[info]   Reference: SIZE: 4
[info]   PATH: /var/folders/h7/qlkb647s6dz25j170cq240tw0000gn/T/glob-tests7494021232790431127/globtree/a/a.txt
[info]   PATH: /var/folders/h7/qlkb647s6dz25j170cq240tw0000gn/T/glob-tests7494021232790431127/globtree/a/a2/a2.txt
[info]   PATH: /var/folders/h7/qlkb647s6dz25j170cq240tw0000gn/T/glob-tests7494021232790431127/globtree/a/a2/x.txt
[info]   PATH: /var/folders/h7/qlkb647s6dz25j170cq240tw0000gn/T/glob-tests7494021232790431127/globtree/a/x.txt
[info]   0 did not equal 4 (GlobSpec.scala:133)
```

**Comment by jaa127** [comment]
Hi, I tried to reproduce the problem, but everything is fine here (Linux, ext4 / tmpfs). Which OS, filesystem etc. do you use?

**Comment by SethTisue** [comment]
OS: macOS 10.12.5, filesystem: Journaled HFS+

**Comment by SethTisue** [comment]
green at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1738/consoleFull after https://github.com/scala/community-builds/commit/7ff9aa9933cfdfcf0a47210108e51a345679fe6a 👍

**Comment by jaa127** [comment]
OTOH, #120 might be broken again, but I can't test on windows nor macOS at the moment. The problem is that path sep must be regexp escaped if it is backslash.

**Comment by pathikrit** [comment]
It runs fine on Ubuntu (on CircleCI) and on macOS (my laptop). I don't have access to Windows. Since IO is one of those things that can break per OS, @SethTisue - does community builds have access to Windows? Maybe the Scala Platform Process does (cc: @jvician)?

@jaa127 - my guess it would be fine on Windows because of this line: https://github.com/pathikrit/better-files/blob/master/core/src/main/scala/better/files/File.scala#L1100

**Comment by jvican** [comment]
@pathikrit No, it doesn't, but I think it's a good idea to have both the Scala Platform CI alongside a Windows CI. The Scala Platform CI will be the responsible for cutting releases et al, whereas the Windows CI will only run tests on Windows.
  
For an example to set up the CI server for Windows, [check](https://github.com/sbt/zinc/pull/370).
