### ISSUE TITLE
createIfNotExists breaks on symlinks to directories e.g. /tmp on Windows and Mac

### ISSUE THREAD

**Issue by gurghet** [pathikrit/better-files#171]
``` scala
import $ivy.`com.github.pathikrit::better-files:3.0.0`, better.files._
File("/tmp/file.txt").createIfNotExists(createParents = true)
// java.nio.file.FileAlreadyExistsException: /tmp
```
This fails because the native function inside UnixNativeDispatcher.class `mkdir0({/tmp}, 511)` fails. Where {/tmp} is the address of the iNode and 511 is the mode (`r-x--x--x`)

**Comment by pathikrit** [comment]
Hi, I cannot reproduce it on my Mac (and the test passes on Ubuntu on CI). See: https://github.com/pathikrit/better-files/pull/172

**Comment by gurghet** [comment]
Yeah thank you. That tests works for me too. Its specifically the lines I have posted that don't work. So the `tmp` directory. What does `File.temporaryDirectory()` yield in your tests?

**Comment by pathikrit** [comment]
Hmm, forget better-files, do this:

```scala
import java.nio.file.{Files, Paths}
Files.createDirectories(Paths.get("/tmp"))
```

It throws:
```
Exception in thread "main" java.nio.file.FileAlreadyExistsException: /tmp
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:727)
```

This is weird since the [Javadoc says](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#createDirectories(java.nio.file.Path,%20java.nio.file.attribute.FileAttribute...) it would only throw a `FileAlreadyExistsException` if dir exists but is not a directory (optional specific exception)

**Comment by pathikrit** [comment]
Looks like it is a bug in Java itself:
http://bugs.java.com/view_bug.do?bug_id=8032220

This is because of the fact that `/tmp` is a symlink in most OS. See: https://bugs.openjdk.java.net/browse/JDK-8130464
