### ISSUE TITLE
Autoclose change in 3.1.0?

### ISSUE THREAD

**Issue by lespea** [pathikrit/better-files#174]
Not sure what changed between 3.0.0 and 3.1.0 but this no longer compiles with the new release.  Not sure how to even make it compile now.

```
import better.files._

object Main extends App {
  for {
    in  ← Main.getClass.getResourceAsStream("/in.txt").autoClosed
    out ← File("out.txt").outputStream
  } in > out
}
```

**Comment by pathikrit** [comment]
All the symbolic operations are now 2nd class (you have to import `better.files.Dsl._`). I would recommend to staying away from symbols as they are now frowned upon. To make your code compile replace `in > out` with `in.pipeTo(out)`:

```scala
import better.files._

object Main extends App {
  for {
    in  ← Main.getClass.getResourceAsStream("/in.txt").autoClosed
    out ← File("out.txt").outputStream
  } in.pipeTo(out)
}
```

**Comment by pathikrit** [comment]
Also you don't have to do `Main.getClass.getResourceAsStream("/in.txt")`, in better-files you can simply do `resourceAsStream("/in.txt")`

**Comment by lespea** [comment]
Okay that worked, thanks!  The resourceAsStream was just for the example, I was processing input streams that were being returned by a different library call in my codebase.
