### ISSUE TITLE
Akka FileWatcher won't stop

### ISSUE THREAD

**Issue by acunniffe** [pathikrit/better-files#188]
I'm trying to kill a file watcher after its no longer needed (this is affecting the performance of my app). 

I've tried everything that appears to stop the actor and yet my test using the Akka Testkit still receive messages when they shouldn't. 

`FileWatcher.stop(EventType.ENTRY_CREATE, callback)`  - does not work
`watcher ! Kill` - does not work
`watcher ! Stop` - does not work
`watcher ! PoisionPill` - does not work
`watcher ! stop(EventType.ENTRY_CREATE, callback)` - does not work 
And here's how I'm setting it up:

```
private val watcher: ActorRef = baseDirectory.newWatcher(recursive = true)
  def watch = {
    watcher ! when(events = EventType.ENTRY_CREATE, EventType.ENTRY_MODIFY, EventType.ENTRY_DELETE)(callback)
  }

  private val callback : better.files.FileWatcher.Callback = {
    case (EventType.ENTRY_CREATE, file) => {
      updateWatchedFiles
      if (watchedFiles.contains(file)) projectActor ! FileCreated(file)
    }
    case (EventType.ENTRY_MODIFY, file) => if (watchedFiles.contains(file)) projectActor ! FileUpdated(file)
    case (EventType.ENTRY_DELETE, file) => {
      if (watchedFiles.contains(file)) projectActor ! FileDeleted(file)
      updateWatchedFiles
    }
  }
```

and the failing test:
```
it("can stop watching files") {
       //see above for things I've tried to stop the watcher
       Thread.sleep(100) //for good measure. 
        File(getCurrentDirectory + "/src/test/resources/tmp/otherFile").createIfNotExists(false)
        expectNoMsg(2 seconds)
}
```

Ideally I'd like to start/stop the actor at will.

**Comment by pathikrit** [comment]
Actors are shutdown **asynchronously **i.e. there might be some time during which messages can still processed even if you issued shutdown to actor. I added a test to show this:
```scala
system.stop(fileWatcher)
// doIO
// fileWatcher still reacts
```

But you need to do this:
```scala
system.stop(fileWatcher)
sleep()
// doIO
// fileWatcher does not react!
```

See: https://github.com/pathikrit/better-files/pull/190/files
