### ISSUE TITLE
The << function should not add an extra platform dependant newline

### ISSUE THREAD

**Issue by jvr-ks** [pathikrit/better-files#19]
import better.files._
import java.io.{File => JFile}

val f1 = file"test1.txt"
f1 < "hello "
f1 << "world "
f1 << "how are you"
f1 << "?"

println(f1.contentAsString)

/*
should print:
hello world how are you?
 
but prints:
 
hello world 
how are you
?
*/

**Comment by jvr-ks** [comment]
Oh, looked at the sources, just wraps java.nio.Files write...

**Comment by pathikrit** [comment]
You can use `f1.append("?")` which does not introduce a new line
