### ISSUE TITLE
createDirectories()/createDirectories() shouldn't swallow FileAlreadyExistsException if the file that exists is not a directory

### ISSUE THREAD

**Issue by woky** [pathikrit/better-files#195]
This is wrong:

```
  def createDirectory()(implicit attributes: File.Attributes = File.Attributes.default): this.type = {
    try {
      Files.createDirectory(path, attributes: _*)
    } catch {
      case _: FileAlreadyExistsException => // We don't really care if it exists already
    }
    this
  }

  def createDirectories()(implicit attributes: File.Attributes = File.Attributes.default): this.type = {
    try {
      Files.createDirectories(path, attributes: _*)
    } catch {
      case _: FileAlreadyExistsException => // We don't really care if it exists already
    }
    this
  }
```

`Files.createDirectories()` already handles the case where the directory exists. Both `Files.createDirectory()` (aka `mkdir`) and `Files.createDirectories()` (aka `mkdir -p`) throw `FileAlreadyExistsException` if a path component already exists and isn't a directory:

```
$ touch /tmp/foo
$ mkdir /tmp/foo
mkdir: cannot create directory ‘/tmp/foo’: File exists
$ mkdir -p /tmp/foo
mkdir: cannot create directory ‘/tmp/foo’: File exists
$ mkdir -p /tmp/foo/bar
mkdir: cannot create directory ‘/tmp/foo’: Not a directory
```

Please, don't hide errors if you don't understand consequences.

**Comment by pathikrit** [comment]
Why would you care if the thing you are trying to create already exists or not - the scaladoc clearly states that it creates the directory if it does not exist already.

**Comment by woky** [comment]
Because the existing path can be a file. In that case, directory won't be created and the code fails somewhere else, because it'll treat path to existing file as path to existing directory. O_o The Java NIO methods are correct.

**Comment by pathikrit** [comment]
I don't think the Java NIO methods are correct too (see #171). I think this is the correct behavior - if `FileAlreadyExistsException` is thrown make sure that the existing file is of the same type (i.e. if you were trying to create a directory, it is a directory) otherwise throw the exception

**Comment by woky** [comment]
But your code (`createDirectories()`/`createDirectories()`) doesn't do any such checks while Java NIO ones (`createDirectories()`/`createDirectories()`) do and signal the condition `FileAlreadyExistsException` which you just swallow and pretend everything is fine. What exactly is point of these two functions? They both do the same and they do it wrong.

**Comment by pathikrit** [comment]
All I am saying is that we should not throw an exception if we tried to create a directory and the directory already exists. If we tried to create a directory but a file exists at that path - then you are right we should propagate that exception but I disagree with you if you tried to create a directory and directory exists we should throw exception

**Comment by woky** [comment]
In the case of `createDirectory()` yes, you should. That's the contract of `mkdir(2)` which `Files.createDirectory()` follows. There are cases where you may need to know that the directory already exists. It may have different access rights for example. How can you call this project _thin Scala wrapper around Java NIO_ when it changes semantics of NIO functions?

**Comment by pathikrit** [comment]
I strongly disagree with you because: 

a) There are many inadequacies in the Java library and we should not blindly follow what the JDK library does - no major project I have seen uses Java NIO directly even in the Java world - people usually use Guava or Apache IO. 

b) _thin Scala wrapper around Java NIO_  - The thin wrapper implies that there is no external dependency and no new concepts or classes but what it does - it smoothes inconsistencies in the Java library like this.

b) If the caller does care about the case where if a directory already exists when creating it, Exception-flow should not be the norm - the caller should check for if directory exists before calling it instead of catching an exception.

**Comment by pathikrit** [comment]
@woky : Please do not use profanity. I am a sole maintainer of this library that is widely used and I try my best to accomodate feature requests and bug fixes.

I have a pull request that does what you say but this opens up #171 then:
https://github.com/pathikrit/better-files/pull/196
