### ISSUE TITLE
make file.lines a stream or something similar

### ISSUE THREAD

**Issue by antonkulaga** [pathikrit/better-files#208]
Quite often I just need to look at first 10-20 lines of file without reading the whole content. I see that lines returns Traversable[String] as an output, that is why I intuitively expect it to be a Stream[String] or something similar, however:
```
  import better.files._
  import java.io.{File => JFile}
  val largeFile = better.files.File("/pipelines") / "uniprot" / "uniref90.fasta"
  val head10 = largeFile.lines.take(10) #crashes with out of memory instead of just reading first 10 lines
```
and in the code I see that lines reads all the file and crashes because the file is too large. I wonder why do not you make it a Stream instead?

**Comment by pathikrit** [comment]
I think you are looking for `.lineIterator`: https://github.com/pathikrit/better-files/blob/c1f37951e96725535d8b1af7ff796889df9015ea/core/src/main/scala/better/files/File.scala#L259
