### ISSUE TITLE
Fail to unzip

### ISSUE THREAD

**Issue by Adrian-Sanz-Alstom** [pathikrit/better-files#216]
Hello, using your last library version() I get the following error on DataBricks (10 days befores code worked and I did not change anything):
java.lang.NoSuchMethodError: better.files.File.unzipTo$default$2()Lscala/Function1;

**Comment by pathikrit** [comment]
Did you change the version of library? The zip API changed lately. See: https://github.com/pathikrit/better-files/blob/master/CHANGES.md
