### ISSUE TITLE
relativize returns empty string instead of "." for current-dir

### ISSUE THREAD

**Issue by arberg** [pathikrit/better-files#223]
val f = better.files.File("/home")
 f.relativize(f).toString == ""

Is this intended behaviour? I'm not sure its a problem, but it was quite surprising to me it does not follow the standard of using ".".

I suppose it does not hurt since in both windows (cmd, powershell) and linux (bash) './/.' and '././.' means the same (with backlslashes for windows cmd)

**Comment by pathikrit** [comment]
This does exactly the same thing as this Java API:

https://docs.oracle.com/javase/7/docs/api/java/nio/file/Path.html#relativize(java.nio.file.Path)

**Comment by arberg** [comment]
Oh right, I didn't realize I could check the Java behaviour, that would have saved your time. 

Best Alex
