### ISSUE TITLE
resourceAsStream buffers the InputStream by default. Why?

### ISSUE THREAD

**Issue by argv-minus-one** [pathikrit/better-files#226]
abccc05 changed `resourceAsStream` to, by default, wrap a `BufferedInputStream` around the `InputStream` received from the `ClassLoader`. Why was this done? Is it still useful? This behavior seems somewhat [astonishing](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), given that the corresponding Java API doesn't do this, and I can't see any reason for it.

I'm working on some additions to `File.resource` and `resourceAsStream`, but I ran into this, and I thought I'd better ask.

**Comment by pathikrit** [comment]
better-files follows the philosophy of the saner/safer default choice. There are cases if you do not buffer, you run into performance issues but it is never unsafe the other way (can you think of a case where buffering may lead to something bad over unbuffered?). That being said, I would be happy to provide the `resourceAsStream` API to provide options to specify buffer size (0 can mean unbuffered).

**Comment by argv-minus-one** [comment]
>better-files follows the philosophy of the saner/safer default choice. There are cases if you do not buffer, you run into performance issues but it is never unsafe the other way

True. That makes sense, so I'll go ahead and close this.

>can you think of a case where buffering may lead to something bad over unbuffered?

Unnecessary buffering wastes memory, but that's not nearly as bad as incorrect use of an unbuffered stream.

>I would be happy to provide the resourceAsStream API to provide options to specify buffer size (0 can mean unbuffered).

You already did, in ec4a9e9. `bufferSize` ≤ 0 currently results in `IllegalArgumentException`, though.

---

In case you're wondering why this came up: I was adding a `classResourceAsStream` method, which looks up the resource relative to the caller's class (or some other `Class[_]`), rather than with the context class loader. To support both getting the caller's class and letting the caller specify some other class, I had to make two overloads of `classResourceAsStream`, both of which take a buffer size…but Scala does not allow multiple overloads to have default parameter values!

Code:

	def classResourceAsStream(
		forClass: Class[_],
		name: String,
		bufferSize: Int = DefaultBufferSize): InputStream = ???

	def classResourceAsStream(
		name: String,
		bufferSize: Int = DefaultBufferSize)
		(implicit caller: CallerClass): InputStream = ???

Error:

	better-files/core/src/main/scala/better/files/package.scala:12:16: in package object files, multiple overloaded alternatives of method classResourceAsStream define default arguments.

I'll need to design this differently, then. 🤔 Thanks for your fast response, by the way!

**Comment by argv-minus-one** [comment]
I wrote a test to verify that `resourceAsStream` returns a `BufferedInputStream` only when `bufferSize > 0`. To my surprise, `ClassLoader#getResourceAsStream` usually returns a `BufferedInputStream` (or `ByteArrayInputStream`) already!

However, the Javadoc for `ClassLoader` doesn't guarantee that the returned `InputStream` will be buffered. Apache Harmony's `URLClassLoader`, for example, appears to return either a buffered or unbuffered `InputStream`, depending on the URL scheme (plain files are buffered; JAR files are only buffered if they're compressed).

So, we should skip constructing a `BufferedInputStream` if the underlying stream matches `_: BufferedInputStream | _: ByteArrayInputStream`, right? Problem: Just because the returned stream is buffered doesn't mean the buffer size is what the application expects, and there's no way to tell what its buffer size actually is. The default buffer size matches that of better-files, but it's not guaranteed.

What do you think should be done? Buffering a `ByteArrayInputStream` is definitely useless, but buffering a `BufferedInputStream` is only *probably* useless.

**Comment by pathikrit** [comment]
I am fine with removing auto buffering and letting the caller call `.resourceAsStream.buffered`
