### ISSUE TITLE
scala 2.13 support

### ISSUE THREAD

**Issue by pshirshov** [pathikrit/better-files#248]
Hi guys, 

any plans on this?

**Comment by pathikrit** [comment]
Is Scala 2.13 out?

**Comment by pathikrit** [comment]
I will release it when it comes out

**Comment by pshirshov** [comment]
For those who is porting their stuff at the moment it would be just a motivation to drop this project.
Though anyway, thank you for your work.

**Comment by pathikrit** [comment]
Scala 2.13 is not out yet. I will not waste time against some beta.

**Comment by pathikrit** [comment]
Ok, beter-files is now available on Maven for 2.13.0-M5:

https://oss.sonatype.org/content/repositories/releases/com/github/pathikrit/better-files_2.13.0-M5/

**Comment by mfirry** [comment]
2.13.0-RC1 is out now

**Comment by pathikrit** [comment]
Reopenning this for 2.13.0-RC1

**Comment by pathikrit** [comment]
Fixed in #312
