### ISSUE TITLE
Misleading README

### ISSUE THREAD

**Issue by emilypi** [pathikrit/better-files#257]
The first line of the README states the following:

```
better-files is a dependency-free pragmatic thin Scala wrapper around Java NIO.
```

However, if we step into `Dependencies.scala`, we see the following:

```scala
import sbt._

object Dependencies {
  def scalaReflect(version: String) = "org.scala-lang"    % "scala-reflect" % version % Provided
  val akka                          = "com.typesafe.akka" %% "akka-actor"   % "2.5.14" // Used in Akka file watcher
  val scalatest                     = "org.scalatest"     %% "scalatest"    % "3.0.6-SNAP1" % Test
  val shapeless                     = "com.chuusai"       %% "shapeless"    % "2.3.3" % Test // For shapeless based Reader/Scanner in tests
  val commonsio                     = "commons-io"        % "commons-io"    % "2.6" % Test // Benchmarks
  val fastjavaio                    = "fastjavaio"        % "fastjavaio"    % "1.0" % Test from "https://github.com/williamfiset/FastJavaIO/releases/download/v1.0/fastjavaio.jar" //Benchmarks
}
```

Thassalotta dependencies. Many are heavyweight, e.g. `akka` and `shapeless`. Perhaps it's time to update the README? 😄

**Comment by pathikrit** [comment]
No, the "dependency free" claim still stands.

You see all the dependencies have `% Test` which restricts them to the `test` scope i.e. better-files itself does not depend on them but are used in testing only. Thus, the public better-files core does not have these dependencies.

The `akka` one is used in a different module called `better-files-akka` only.
