### ISSUE TITLE
Support files in jar/zip archive files

### ISSUE THREAD

**Issue by dwijnand** [pathikrit/better-files#261]
One of the core strengths of NIO is that it works on abstract filesystems, such as jar/zip files. This has been used to great effect in ENSIME.

It would be wonderful if this use case were supported in better-files.

The ENSIME project would love to use a Scala standard platform library than roll its own, see:

https://github.com/ensime/ensime-server/blob/2.0/util/src/main/scala/org/ensime/util/ensimefile.scala
https://github.com/ensime/ensime-server/blob/2.0/util/src/main/scala/org/ensime/util/path.scala
(deprecating) https://github.com/ensime/ensime-server/blob/2.0/util/src/main/scala/org/ensime/util/file.scala
(deprecating) https://github.com/ensime/ensime-server/blob/2.0/util/src/main/scala/org/ensime/util/io.scala

(BTW, the key to the abstraction is that there needs to be a clean way to close that abstract filesystem. Keeping jars/zips open is really really bad on Windows Windows, see https://github.com/fommil/class-monkey)

<sub>
(I'm opening this issue to replace #121, kindly request that that one to be closed off. Thank you.)
</sub>

**Comment by pathikrit** [comment]
I just don't understand why everyone wants to close #121 without resolving it.

**Comment by dwijnand** [comment]
Ah sorry. So on GitHub at https://github.com/issues you can see all the issues you've created, are assigned, etc. @fommil filed #121 originally, but now is no longer interested in that change, in better-files and the Scala ecosystem in general, and so has closed off all the issues in his https://github.com/issues related to the Scala ecosystem.

Unfortunately in GitHub's issue tracker there's no way to disassociate yourself from an issue you originally filed other than to close it (e.g in Jira you can do this). In other projects the maintainers of the projects have re-filed the issue, to replace the one @fommil closed.

As I understand it #121 is the last scala-related issue in @fommil's https://github.com/issues which he can't get rid of. So I'm proposing let's track this feature in _this_ issue, #261, and close #121 for @fommil. Of course we'll link this issue to #121 so the details there can be read.

Does that sound reasonable to you?
