### ISSUE TITLE
Backslashes in zip entry name

### ISSUE THREAD

**Issue by dionys** [pathikrit/better-files#262]
Some Windows tools creates the zip-archives with the backslashes in the entry names as path separators instead of slashes. E.g.:

    foo\bar.txt
    foo\baz\qux.bin

The *nix tools accepts this format (with warnings like `warning: foo.zip appears to use backslashes as path separators` for `unzip`) and successfully extracts the directory tree. E.g.:

    tmp
    `- foo
       |- bar.txt
       `- baz
          `- qux.bin

But `better-files` can't do this. It extracts paths as is, plain not tree:

    tmp
    |- foo\bar.txt
    `- foo\baz\qux.bin

Simple replace in [`ZipEntryOps.extractTo()` method](https://github.com/pathikrit/better-files/blob/master/core/src/main/scala/better/files/Implicits.scala#L320) might resolve this problem:

    - entry.getName
    + entry.getName.replace("\\", "/")

**Comment by pathikrit** [comment]
I have no way to unit test this - do you have such a zip file you can attach to this issue?

**Comment by dionys** [comment]
PowerShell for example:

    Add-Type -AssemblyName System.IO.Compression.FileSystem
    [System.IO.Compression.ZipFile]::CreateFromDirectory("C:\Temp\foo", "C:\Temp\foo.zip")

[foo.zip](https://github.com/pathikrit/better-files/files/2554653/foo.zip)

**Comment by som-snytt** [comment]
I just had a test in `scala/scala` fail on windows -- it creates a jar with a plugin to load. The reason for the failure was backslashes in entry names due to `Path.toString`:
```
val rel: Path = ???   // relative path
jout.putNextEntry(new JarEntry(rel.toString.replace("\\", "/"))) // fix evil windows backslash
```
It occurred to me to wonder if better-files would help with the backslash curse. Registering my interest here; I haven't gone through the API yet.

As of 2020, I refuse to convert slashes.
