### ISSUE TITLE
FileEncoder support

### ISSUE THREAD

**Issue by JasonShin** [pathikrit/better-files#264]
Hi, thanks for a great library!

Do you have any plans on supporting FileEncoding, probably starting from base64, from better-files?

**Comment by pathikrit** [comment]
Can you give a concrete example? better-files already supports charsets. Look here: 
https://github.com/pathikrit/better-files#encodings

What do you have in mind?

**Comment by JasonShin** [comment]
Hey, I didn't realise it has encoding API support, sorry about the confusion ;)
