### ISSUE TITLE
Need to be able to justify incorporating this library to bank

### ISSUE THREAD

**Issue by JohnReedLOL** [pathikrit/better-files#265]
Sorry to bother you,

I am working on a Scala project and I need to save and use data in fixed width text format. That being said, the bank I work at has a lot of red tape and they don't approve anything unless you convince them to do so. In about a month I'm going to do a demo of the open source libraries that I want them to put into their system. To help me get approval, could you write something explaining that they won't have any issues with copyright or patents and that this library is being actively maintained, is well documented, and has real world business value?

**Comment by pathikrit** [comment]
It has an MIT License: https://github.com/pathikrit/better-files/blob/master/LICENSE so you can use as you please.

You can see the commit history and/or release history here: https://github.com/pathikrit/better-files/releases

The library has update releases every few months.

You can see the documentation for yourself on the README

**Comment by pathikrit** [comment]
In general, you should advocate developers to choose whatever library they want. Do code reviews and hire passionate developers who can self-curate what libraries get in the system. You can show them examples from other top tech companies like Google or Facebook to other top hedge funds like TwoSigma who give their developers this freedom.

**Comment by JohnReedLOL** [comment]
Just having the MIT License clearly stated is a plus. Not all developers have the freedom to pick up and use any open source software that they want.
