### ISSUE TITLE
Make examples work

### ISSUE THREAD

**Issue by JohnReedLOL** [pathikrit/better-files#266]
Your first code example should work seamlessly.

[https://i.imgur.com/S1djf5r.png](https://i.imgur.com/S1djf5r.png)

**Comment by JohnReedLOL** [comment]
And another:

[https://i.imgur.com/ypNz2nV.png](https://i.imgur.com/ypNz2nV.png)

**Comment by JohnReedLOL** [comment]
Another error: [https://i.imgur.com/NrtJzqA.png](https://i.imgur.com/NrtJzqA.png)

**Comment by JohnReedLOL** [comment]
Another typo:

`must import import better.files.Dsl.SymbolicOperations`

**Comment by pathikrit** [comment]
Covered by #12
