### ISSUE TITLE
Dispose[FileOutputStream] creates invalid files

### ISSUE THREAD

**Issue by vimalaguti** [pathikrit/better-files#271]
When saving a protobuf  the resulting file cannot be read. If I do:

`file.fileOutputStream {stream => protobuf.writeTo(stream)} `

the resulting file is a bit smaller (and cannot be read) then when I manually do:

```
val stream = file.newFileOutputStream
protobuf.writeTo(stream)
stream.close
```

Am I using it in the wrong way or there is a bug?

**Comment by pathikrit** [comment]
You forgot the foreach! 
Either of this should work:

```scala
for {
    fout <- file.fileOutputStream()
  } protobuf.writeTo(fout)
```

or simply:
```scala
file.fileOutputStream().foreach(protobuf.writeTo)
```
