### ISSUE TITLE
Cannot change extension to non existent file

### ISSUE THREAD

**Issue by vimalaguti** [pathikrit/better-files#272]
Sometimes I build the output path by steps, and when I try to set the extension of a file that yet doesn't exists, the changeExtensionTo actually do nothing.

eg.

```
File.temporaryDirectory()` { dir => 
val outBase = dir / baseName
.....
val outFile = outBase.changeExtensionTo(".ext")
 }
```

the resulting outFile is without extension.
But if I create the file first `outBase.createFile()` then it works fine

**Comment by pathikrit** [comment]
I will update the doc but it should not do anything if file does not exist (or is a directory). It is a good practice to to this:
```scala
val outBase = (dir / baseName).createIfNotExists()
val outFile = outBase.changeExtensionTo(".ext")
```
