### ISSUE TITLE
Adding method 'sibling'

### ISSUE THREAD

**Issue by r0estir0bbe** [pathikrit/better-files#33]
Consider adding functionality for calling method `file.sibling` directly on `File`, i.e.

```scala
def sibling(other: String): File = path.resolveSibling(other)
```

I use this functionality separately of `file.renameTo` and have (currently) implemented with an implicit class.

**Comment by pathikrit** [comment]
Added: https://github.com/pathikrit/better-files/blob/28d8c2bbc64eec122834de230715deaf61997249/core/src/main/scala/better/files/File.scala#L67-L71

**Comment by r0estir0bbe** [comment]
Fast and neat. Did not expect anything else from this library. Thanks a lot!
