### ISSUE TITLE
Would you be interested in abstracting over return type?

### ISSUE THREAD

**Issue by Krever** [pathikrit/better-files#343]
I would like to know if you (maintainers) would be interested in having API similar to `scalacache` in terms of return type? For details please check: https://cb372.github.io/scalacache/docs/modes.html
So the import specifies if we will get `Try`, `Future` or `F[_]` from operations.

I think its rather big and breaking change, yet I'm looking for pure FP file library at the moment and wouldn't like to create anything new if not absolutely necessary.

**Comment by pathikrit** [comment]
The design goal of this library is to provide a simple, no-surprise layer over Java NIO. I don't think putting Try or Future or F is a wise idea. Look at Google Guava or Apache Commons IO. Both these Java libraries have IOUtils and they don't do these Try/Future/F stuff - they just do I/O and are widely used in major companies. better-files has same goal - just have I/O util type stuff and any higher level wrapping is left to the caller to decide

**Comment by Krever** [comment]
Great, this is kind of answer I was looking for! Sadly I didn't know the exact design goals in this matter. Your approach is fully understandable! Thanks for your work ;)
