### ISSUE TITLE
NoClassDefFound: java/sql/Date using JDK 11

### ISSUE THREAD

**Issue by DPachs** [pathikrit/better-files#346]
I'm getting a NoClassDefFoundError using IntelliJ with JDK 11. 

I have read that there's some deprecated methods on the sql/Date class, but the class itself is not deprecated, so it should be available for me. Everything was working good before i migrated to Java 11. A similar error was ocurring with the javafx classes, but i was able to fix it importing the jdk manually.

stacktrace:

> Caused by: java.lang.NoClassDefFoundError: java/sql/Date
> 	at better.files.Scanner$Read$Implicits.$init$(Scanner.scala:96)
> 	at better.files.package$.<init>(package.scala:9)
> 	at better.files.package$.<clinit>(package.scala)
> 	at better.files.File$.home(File.scala:1456)
> 	at visao.LabVisual$$anon$20.<init>(LabVisual.scala:92)

**Comment by pathikrit** [comment]
This has nothing to do with better-files but the Java module system introduced in Java 9. See how to solve this here: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360003549920-Getting-class-not-found-exception-after-shifting-to-JDK-11

**Comment by echavez-eb** [comment]
> This has nothing to do with better-files but the Java module system introduced in Java 9. See how to solve this here: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360003549920-Getting-class-not-found-exception-after-shifting-to-JDK-11

... I did what the instructions in the link tell. Didn't resolve the issue.

**Comment by pathikrit** [comment]
@echavez-eb :

What does this look like for you:

https://image.slidesharecdn.com/migratingtojava9modules-171006052108/95/migrating-to-java-9-modules-29-638.jpg?cb=1507267987

What is your error?
