### ISSUE TITLE
Appending to Zip Filesystem

### ISSUE THREAD

**Issue by reynoldsm88** [pathikrit/better-files#354]
I saw [this previous issue](https://github.com/pathikrit/better-files/issues/121) and was wondering if it was someway possible to write to a zip file without repackaging, or if support for this is something that's doable (I know @pathikrit mentions that this library was to abstract over `java.io.File`, and therefore does not include the `java.nio` stuff introduced in Java 7).

However, if it is possible it would be nice if this functionality would be supported somehow. We have actually tried to standardize on `better-files` for handling files across our entire platform... however, we have a few modules that for size and performance reasons need to write directly to zipped files, and there we wind up having to use the Java libraries.

**Comment by reynoldsm88** [comment]
Looks like I found an answer to my own question, with no help from the [rabbit hole of misleading oracle docs](https://docs.oracle.com/javase/7/docs/technotes/guides/io/fsp/zipfilesystemprovider.html)

Wound up doing this, which is pretty simple and documented more or less in the README...

```scala
override def writeFile( filename : String, content : String ) : Unit = {
        val out : ZipOutputStream = archiveFile.newZipOutputStream
        out.putNextEntry( new ZipEntry( s"${archiveFile.name}/${filename}" ) )
        out.write( content.getBytes )
        out.closeEntry()
        out.close()
    }
```

**Comment by pathikrit** [comment]
@reynoldsm88 : There is an easier way to do this in better-files. See line 320: https://github.com/pathikrit/better-files/blob/master/core/src/main/scala/better/files/Implicits.scala#L320

```scala
archiveFile.zipOutputStream).foreach(_.add(fileName))
```
