### ISSUE TITLE
how efficient is File Monitoring ??

### ISSUE THREAD

**Issue by cocodrino** [pathikrit/better-files#36]
Hi, I'm interested in use file monitoring for check file changes in a disk of several TB (2 or 3 TB), do you know how expensive could be in terms of memory/cpu usage??..thank you!..

**Comment by pathikrit** [comment]
It would be as expensive as the Java 8 WatchService: http://docs.oracle.com/javase/8/docs/api/java/nio/file/WatchService.html
and it adds no real overhead on top of that.

Please use the chatroom https://gitter.im/pathikrit/better-files to discuss questions like this. Open Github issues for feature requests or bug reports. Thanks!
