### ISSUE TITLE
Requesting a method to return OS temporary directory

### ISSUE THREAD

**Issue by hmf** [pathikrit/better-files#374]
This is a feature request. Just as we have `root` and `cwd` can we have a `tmp` that returns the OS's temporary directory? Several [options](https://stackoverflow.com/questions/617414/how-to-create-a-temporary-directory-folder-in-java) exist. The following seems to be a popular solution:

```
val property = "java.io.tmpdir"
val tempDir = System.getProperty(property)
```

TIA

**Comment by pathikrit** [comment]
This already exists. See: https://github.com/pathikrit/better-files/blob/3b3f2eda64fedd4999ed820d0fe05d9141107fad/core/src/main/scala/better/files/File.scala#L1443

```
File.temp
```

**Comment by hmf** [comment]
Oops. Sorry.
