### ISSUE TITLE
hasExtension should not check for `isRegularFile`?

### ISSUE THREAD

**Issue by eikek** [pathikrit/better-files#39]
Hi,

I played around with filename functions regarding the extension and saw that `hasExtension` (which is used often from other functions) checks for `isRegularFile`. In my opinion this is not so good :-) I'd say that these functions operate on names, so even if this “file” is a directory or link, I would expect the file extension concept to apply equally? And as a side effect it checks for file existence, so these functions don't work for non-existing files….

WDYT?

**Comment by pathikrit** [comment]
Fair point that it should not do any OS file calls. But, does it even make sense for a directory to have an extension? I guess not but what you are proposing is that the caller should handle it (i.e. calling extension on a directory) if she wants to?

**Comment by pathikrit** [comment]
I agree, at the very least, this API should work for non-existent files. But, what should I return for `def extension` when the file exists and is a directory called `foo.bar` ?

**Comment by eikek** [comment]
Yes, I'm also not sure what an extension for a directory is supposed to mean. I guess it doesn't make any sense…. But I see the extension as part of a name – without considering what this name is for. So yes, I would propose to not care about whether a name names a directory or not. If `foo.bar` is a directory, I would return `bar` when calling `def extension`.  For non-existent files, one doesn't know what kind of file the name is for. So if this api would work for non-existent files, I don't see a point in checking the file type for existent files. Just my point of view …
