### ISSUE TITLE
Enhance CloseableOps.autoClosedIterator to autoClose when the next method throws an exception?

### ISSUE THREAD

**Issue by r0estir0bbe** [pathikrit/better-files#41]
The utility method `autoClosedIterator` can leave the managed resource open. This can happen if the provided function `next` throws an exception. The code sample in the ScalaDoc is exactly such an example:
```
inputStream.autoClosedIterator(_.read())(_ != -1).map(_.toByte)
```

`InputStream.read` can throw an `IOException` meaning that the method `isOpen` of `autoClosedIterator` will not be called afterwards and thus not close the resource in every case.

One possible way to handle this is to wrap `Try` around the `next` function and adjust the `hasNext` accordingly. E.g. for the above example:

```
inputStream.autoClosedIterator(is => Try(is.read()))(_.getOrElse(-1) != -1).map(_.toByte)
```

The question is whether this is something the caller or the callee has to deal with.

**Comment by pathikrit** [comment]
I would not call this a bug but I agree, this is some additional safety the library can provide. Will take this as an enhancement we can definately do.
