### ISSUE TITLE
FileSystemNotFoundException while reading resources

### ISSUE THREAD

**Issue by baaa** [pathikrit/better-files#412]
I know this happens because inside the jar the actual "file" uri and the system is different, and without using better-files when reading a single file using `getResourceAsStream` works, but following snippet looks simple enough, and am I too naive to assume this should've worked with better files instead of throwing a `FileSystemNotFoundException`
```
val folder = Resource.getUrl("someFolderInResources")
filesInThatFolder = File(folder)..list.toList.map(_.name)
```

**Comment by osocron** [comment]
I'm having the same issue. @baaa were you able to find a fix for the problem?
