### ISSUE TITLE
Document usage of right associative operators correctly

### ISSUE THREAD

**Issue by holgerbrandl** [pathikrit/better-files#43]
I've tried to work through the great examples from your README.md and all work except for 
```
import better.files._
val testFile = file"test.txt"
"hello" >: testFile
```
which reports a  syntax error:
```
<console>:1: error: ';' expected but '>:' found.
"hello" >: testFile
```
I don't see what's wrong with it. Do I need to import some flag to allow for an advanced language feature first?

In contrast
```
"hello" >>: testFile
```
works fine, so my general setup seems fine.

I'm working with Scala version 2.11.7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_60) and v2.13.0 of better-files.

**Comment by pathikrit** [comment]
Try:
```scala
"hello" `>:` testFile
```

I will update the docs meanwhile.

**Comment by holgerbrandl** [comment]
Does not work either for me. Could it be that >: is a reserved symbol (for the lower view bound I think) ? See bottom of p4 of  http://www.scala-lang.org/docu/files/ScalaReference.pdf
or http://stackoverflow.com/questions/7888944/scala-punctuation-aka-symbols-and-operators

**Comment by pathikrit** [comment]
Are you sure? I use it in the unit tests just fine. See: https://github.com/pathikrit/better-files/blob/cb41e6b22dec0729aebed7b75834ba94684bb8ea/core/src/test/scala/better/files/FileSpec.scala#L102

**Comment by holgerbrandl** [comment]
You're right it works as it is. I accidentally tried single quotes and not backticks (since the method named with a Literal identifiers, see http://www.tutorialspoint.com/scala/scala_basic_syntax.htm). However, I think it lacks some elegance and may even add some confusion to reuse a reserved language keyword as a literal identifier.

**Comment by pathikrit** [comment]
Well, you can always use `file.write("hello")` instead of `"hello" >: file` ... Its just symmetric to the `>>:`...
