### ISSUE TITLE
Question: Should we switch to CodacyCoverageReporter since codacyCoverage is deprecated?

### ISSUE THREAD

**Issue by i10416** [pathikrit/better-files#458]
CodacyCoverage seems to be no longer maintained. Should we switch to [codacy-coverage-reporter](https://github.com/codacy/codacy-coverage-reporter)?

**Comment by pathikrit** [comment]
Yes. Thank you for noticing this.

**Comment by ItoYo16u** [comment]
No worries. Thank you for response.

**Comment by pathikrit** [comment]
Just removed Codacy in https://github.com/pathikrit/better-files/commit/d82c1898928cf07fb9bc39d75f721f5f7ae2d1e8
