### ISSUE TITLE
make File serializible

### ISSUE THREAD

**Issue by antonkulaga** [pathikrit/better-files#461]
I sometimes use local files with spark, however I have to use ammonite which is less convenient than betterfiles because File unlike ammonite Path is not serializible, it would be nice if it would become serializible

**Comment by pathikrit** [comment]
What version are you using? This has been resolved by #249

**Comment by antonkulaga** [comment]
@pathikrit 3.9.1 and it still causes serialization problems

**Comment by pathikrit** [comment]
Closing this since this is an issue with Spark - java.io.File is not serializable with Spark UDFs. better-files is just a thin wrapper around java.io.File
