### ISSUE TITLE
`toString` should be actual local path and not URI

### ISSUE THREAD

**Issue by holgerbrandl** [pathikrit/better-files#48]
The b-f API is tailored to local files (just check the README) so naturally users will expect `better.files.File` instances to render into local filesystem paths (`/home/user/test.txt`) instead of URIs (`file:///home/user/test.txt`). 

For sure there are usecases where URIs have their benefits but the vast majority of users is likely to work with local files only. And as the name suggest better-**file**s a file and not a network api.

It's imho even not really correct to use URI because a relative instance  `File("my.file")` might not be rooted in a file-system at all (until absolute/full path is queried for it) so it should render as "my.file" and not as "file:///current/working/directory/my.file"

In the latest revisions fullPath has been renamed to `pathAsString` which indicates that such a backward-compatibility-breaking change should be possible. :-)

**Comment by pathikrit** [comment]
I thought about this. I wanted to leave the door open for future filesystems e.g. `s3:///foo/bar`. More realistically, it could be a file inside a zipped file e.g. `zip://foo.zip/!filename` etc. Those who expected the `/home/user/test.txt` should call `.pathAsString` to be more explicit anyway since `.toString` of a file is not obvious what it should be by itself?

**Comment by pathikrit** [comment]
Check this out:

```scala
scala> case class Person(name: String)
defined class Person

scala> Person("Bob")
res0: Person = Person(Bob)

scala> res0.toString
res1: String = Person(Bob)
```

By, the above logic, the idiomatic `.toString` for files should be `s"File($path)"` e.g. `File(/tmp/foo/bar)`. If that is true, then the uri version seems better to me.

**Comment by holgerbrandl** [comment]
Indeed case classes you different default toString, however to make b-f a convenient replacement for built-in java.io.File/java.nio.file.Path, b-f should mimic those were possible. So consider

```
scala> // Using "old" java.io.File API

scala> import java.io.File
import java.io.File

scala> val someFile = new File("foo")
someFile: java.io.File = foo


scala> val derivedFile = new File(someFile, "bar")
derivedFile: java.io.File = foo/bar

scala> // Using java.nio.file.Path API

scala> import java.nio.file._
import java.nio.file._

scala> val path = Paths.get("somthing")
path: java.nio.file.Path = somthing


scala> val childEl = path.resolve("else.txt")
childEl: java.nio.file.Path = somthing/else.txt

scala> // Using BF API

scala> val betterFile = better.files.File("foo")
betterFile: better.files.File = file:///Users/brandl/Dropbox/cluster_sync/scalautils/foo

scala> val betterDerivedFile = betterFile/"bar"
betterDerivedFile: better.files.File = file:///Users/brandl/Dropbox/cluster_sync/scalautils/foo/bar
```

Or just the code 
```
// Using old java file API
import java.io.File

val someFile = new File("foo")
val derivedFile = new File(someFile, "bar")


// Using Path API
import java.nio.file._

val path = Paths.get("somthing")
val childPath = path.resolve("else.txt")


// Using BF API
val betterFile = better.files.File("foo")
val betterDerivedFile = betterFile/"bar"
```


b-f is neither using the same toString (which would be just the (optionally relative) path and not the uri)  nor is it keeping path-relativity. Both are important features I think, which java-designers obvioulsy carefully preserved when rewriting File into Path API.

**Comment by pathikrit** [comment]
Although IMO, `.toString` is meaningless since its just an arbitrary representation of an object and you should not trust or depend on it for anything except debugging purposes, but I will reopen this issue for the sake of meeting the expectation user's expecting the Java files behaviour

**Comment by holgerbrandl** [comment]
Codewise it should be easy to implement. It seems that reducing
```
  val path = _path.normalize.toAbsolutePath
```
to
```
  val path = _path
```
does the trick without breaking code or tests. The only other change would be to tweak the File.toString to use path.toString instead, which would require a single unit test (better/files/FileSpec.scala:71) to be adjusted.

`File.pathAsString` could be removed since it would equal toString

A useful/necessary addition to `better.files.File` would be 
```
def absoluteFile = path.normalize.toAbsolutePath
``` 
to provide a means to *derelativize* a b.f.File instance (which is at the moment applied in the constructor but not always wanted/needed)

I've played around with such a modified version and it feels very good and consistent and indeed like a **better** java.jo.**File**/Path API.

I'd be happy to create a pull request but it's just changing a few words so it's barely worth the effort. :-)
