### ISSUE TITLE
Scala3 version

### ISSUE THREAD

**Issue by ronanM** [pathikrit/better-files#506]
Is there a plan for Scala3 version ?

**Comment by pathikrit** [comment]
No plans yet but open to PRs

**Comment by SethTisue** [comment]
Looks like the next step a volunteer should take would be to replace Travis-CI with GitHub Actions. Then the many open version-bump PRs could be merged, and that would pave the way for work on Scala 3.

**Comment by mcanlas** [comment]
@SethTisue https://github.com/pathikrit/better-files/pull/529

**Comment by exoego** [comment]
Hi. I've volunteered to add Scala 3 support in #573.

**Comment by exoego** [comment]
@pathikrit Could you take a look on #573 that adds Scala 3 support

**Comment by pathikrit** [comment]
@exoego : Thank you! Will take a look shortly
