### ISSUE TITLE
is there a way to read huge gz csv file line by line of this package?

### ISSUE THREAD

**Issue by LizzyMiao** [pathikrit/better-files#577]
I am wondering if this package provides a good way to read huge gz csv file and extract the string content of each line into a case class?

**Comment by pathikrit** [comment]
You can read a huge csv gz file but parsing into case class needs a CSV parsing library.

You can do the first part in better-files as follows:
```
import better.files._
val lines: Iteratory[String] = File("huge.csv.gz").newGzipInputStream().lines
```
