### ISSUE TITLE
add file ordering

### ISSUE THREAD

**Issue by intracer** [pathikrit/better-files#64]
Java's `Path` is `Comparable`: `public interface Path extends Comparable<Path>`
and can be `.sorted`, so here better-files requires a little more code

**Comment by pathikrit** [comment]
Its actually even shorter in better-files and more powerful. See: https://github.com/pathikrit/better-files/blob/b6e772c3372ecf7bbf7bac59780c0fea967d6684/core/src/main/scala/better/files/File.scala#L604-L613

**Comment by pathikrit** [comment]
Here is the Scaladoc: http://pathikrit.github.io/better-files/latest/api/#better.files.File$$Order$
you can use it like `files.sort(File.Order.byName)` for example.
