### ISSUE TITLE
Support writing Iterator[Byte] to File

### ISSUE THREAD

**Issue by pishen** [pathikrit/better-files#67]
Sometimes we may generate a large amount of Strings by `Iterator[String]` and write them to a File without caching all the generated Strings in memory. Will be great if better-files supports an easy way to do this.

**Comment by pathikrit** [comment]
Many large files are not always strings (e.g. a movie). Should this API then take in a `Iterator[Byte]` then?

**Comment by pishen** [comment]
Agree. But could it also support easily (or implicitly) transformation from `Iterator[String]` to `Iterator[Byte]`? Not sure if it should insert the `\n`s in between the Strings automatically?
Since better-files supports simple function like `File.appendLines()`, I hope there's also a similar simple way when appending an `Iterator[String]`.

**Comment by pathikrit** [comment]
Let's say you have an `val lines: Iterator[String]`, you can simply do this:

```
val lines: Iterator[String] = ???
lines foreach {line => file.appendNewLine(line)}
```

That being said, I do see a case for writing an `Iterator[Byte]` to a file ...

**Comment by pishen** [comment]
As I know, `Files.write()` will open and close the file on each call, using `lines foreach {line => file.appendLine(line)}` may not be efficient if my `Iterator[String]` is large? I'm looking for a solution as simple as this, but more efficient.
Anyway, this could be another feature request, I can change this one to `Iterator[Byte]` to keep it precise.

**Comment by pathikrit** [comment]
You are right. We need two APIs that can write:

1. `Iterator[Byte]` e.g. for piping in large movies
2. `Iterator[String]` -- this is for line by line. We need two versions of this - one to append and another to write.

**Comment by pathikrit** [comment]
Take a look at my PR: https://github.com/pathikrit/better-files/pull/70

I added `writeBytes` and `printLines`. The latter takes in options to either append or overwrite.

**Comment by pishen** [comment]
Would it be possible to use the same function name like this?
```
def write(bytes: Array[Byte])
def write(bytes: Iterator[Byte])

def appendLines(lines: String*)
def appendLines(lines: Iterator[String])
```

**Comment by pathikrit** [comment]
That won't compile - you can't have same function name with same number of arguments.

**Comment by pishen** [comment]
Cool! Thanks for supporting this feature.

**Comment by pathikrit** [comment]
Will release v2.16.0 over the weekend
