### ISSUE TITLE
touch() does not work under a relative link directory

### ISSUE THREAD

**Issue by holgerbrandl** [pathikrit/better-files#69]
The following example
```
val wd = (home / "unit_tests").createIfNotExists(asDirectory = true)
(wd / "some_data.txt").touch()
```
gives
```
java.nio.file.FileAlreadyExistsException: /home/brandl/unit_tests
	sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	java.nio.file.Files.createDirectory(Files.java:674)
	java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	java.nio.file.Files.createDirectories(Files.java:727)
	better.files.File.createDirectories(File.scala:96)
	better.files.File.createIfNotExists(File.scala:65)
	better.files.File.touch(File.scala:338)
	cmd36$.<init>(Main.scala:275)
	cmd36$.<clinit>(Main.scala:-1)
```
when `unit_tests` is a symbolic link
```
ll ~/unit_tests
lrwxrwxrwx 1 brandl mygroup 40 May  3 15:20 /home/brandl/unit_tests -> /somewhere/misc/unit_tests
```

Seems more a jdk issue, but maybe there's an easy workaround which bf could implement.

**Comment by pathikrit** [comment]
Good catch. The root cause was that `createIfNotExists` should accept an option to follow symlinks or not. Fixed.

**Comment by holgerbrandl** [comment]
I still don't really understand why `touch()` must create parent directories. Thats not how bash `touch` works, which would fail if the parent is missing. Imho, for consistency with bash the line
https://github.com/pathikrit/better-files/blob/16f3d799e1e288de384b6d71df8371e41ecfffeb/core/src/main/scala/better/files/File.scala#L84
with
```
parent.createDirectories()(attributes)
```
should be removed entirely. 

Imho `createIfNotExists` is also overly when creating a new directory (see l[ine82](https://github.com/pathikrit/better-files/blob/16f3d799e1e288de384b6d71df8371e41ecfffeb/core/src/main/scala/better/files/File.scala#L82)) by creating the entire tree by default, which is something you need to indicate explicitly when using a linux shell `mkdir -p` to prevent mistakes

**Comment by pathikrit** [comment]
@holgerbrandl : You are right. IMO, `touch` does not belong in the Files  class but in the UNIX DSL in Cmds.scala.

For backwards compatibility reasons, I would add a default paramter to `touch` called "create parents" which would be set to false. What do you think?

**Comment by holgerbrandl** [comment]
I think the `createParent` parameter (with false as default) should be rather added to `createIfNotExists()`. This would also fix `touch()` to give a more consistent _bash-experience_

**Comment by pathikrit** [comment]
I think I should do this for maximum flexibility:

1. add `createParent` to createIfNotExists - but the default should be true (to match the behaviour of Java's `Files.createFile()` which it calls).

2. Also add `createParent` to `touch` which it passes to `createIfNotExists` - but in here, it default should be false (to match behaviour of bash).

**Comment by pathikrit** [comment]
SGTM

**Comment by pathikrit** [comment]
Fixed. Will release v2.16.0 over weekend
