### ISSUE TITLE
Hide `Read` typeclass in another package

### ISSUE THREAD

**Issue by guersam** [pathikrit/better-files#76]
I found that `better.files.Read` added in 2.16.0 conflicts with my home-grown `Read`, which exists for exactly the same reason.

As the documentation seems like recommending all-in-one import such as `import better.files._`, I'd suggest that we keep this kind of utilities in a dedicated package like `better.files.util` to avoid unnecessary collisions. WDYT?

**Comment by pathikrit** [comment]
You can resolve this simply by doing this:

```scala
import better.files.{Read => BFRead, _}
``

**Comment by guersam** [comment]
Thanks for the response, that's already what I'm doing for now.

What I'd point out is that since `better.files.Read` is temporal (which will be likely to be removed when https://github.com/typelevel/cats/issues/932 is resolved), It would be more future-proofing to moving it from the project-wise top level scope to a dedicated package such as `util` or `internal` so that users easily can see it's not a part of better-files' stable public API.

I'm willing to open a PR if you think it makes sense, but I don't mind if you don't as I've already applied the suggested workaround.

**Comment by pathikrit** [comment]
I will move it into `better.files.Scanner.Read` then.

**Comment by guersam** [comment]
Thanks!
