### ISSUE TITLE
copyTo function from a dir to a dir empties the target dir when overwrite is true

### ISSUE THREAD

**Issue by JakubKahovec** [pathikrit/better-files#77]
Hi,

I've found out that when I'm calling copyTo from a dir to a target dir it empties the target dir, which seems to me pretty odd behaviour. Normally when one copies files from a source dir to a target dir doesn't expect that the target dir gets erased. 

Jakub

**Comment by jiminhsieh** [comment]
I found when using `copyTo` with overwrite = true, it would simply delete anything in the target directory. If I am correct, I would try to work on this. Thanks!

**Comment by poslegm** [comment]
I think that `if (overwrite) destination.delete(swallowIOExceptions = true)` in `File.copyTo` is useless because files in target dir will be overwrited by `File.CopyOptions(overwrite)`.

`File.copyTo` without this line works like a UNIX `cp` util.

**Comment by pathikrit** [comment]
Fixed in https://github.com/pathikrit/better-files/pull/168
