### ISSUE TITLE
Request: pipeTo without closing the inputstream

### ISSUE THREAD

**Issue by merlijn** [pathikrit/better-files#82]
I ran into some difficulty with this pattern for my use case:

    for {
      input  <- in.autoClosed
      output <- file.newOutputStream.autoClosed
    } input.pipeTo(output)

The result is that the InputStream will be closed twice. 

'Normally' this should not be a problem but I happen to deal with an InputStream that throws an IOException when closing an already closed stream. I would really like an option not to close the input stream in pipeTo. I have a work around, but the code is not as elegant.

**Comment by pathikrit** [comment]
You can just do:

```
in.autoClosed foreach {is =>
  file.outputStream foreach {
    is.pipeTo(os)
  }
}
```
