### ISSUE TITLE
CollectChildren is a little bit unintuitive?

### ISSUE THREAD

**Issue by jvican** [pathikrit/better-files#84]
I'm fiddling with the library and enjoying it a lot.

I stumbled upon until an unintuituive behaviour, that either should be better documented or fixed in the source code. The operation `collectChildren` returns an `Iterator`, so if we don't materialize it or consume it, the code won't be executed. I understand that one may be interested in staging operations, especially in IO, but I would expect any `collect*` to behave as a regular `collect` operation, i.e. eagerly executed. This is especially useful when your code is effectful.

Motivation:

``` scala
"/".toFile.collectChildren {
  case children: File if children.name == "/root" =>
     println(s"BINGO $children")
     true
  case children =>
     println(s"BAD BOY: $children")
     false
} // .toList
```

**Comment by jvican** [comment]
Thinking about it twice, I wouldn't consider this a flaw in the design. I'd just recomment to make these observations more explicit in the official documentation.

**Comment by pathikrit** [comment]
>  I would expect any collect* to behave as a regular collect operation

That's not true even in Scala:

```scala
val t = Iterator("hello", "world").collect{case s => println(s); s}
println(t.toString)
```

vs:

```scala
val t = Seq("hello", "world").collect{case s => println(s); s}
println(t.toString)
```
