### ISSUE TITLE
Publish for Scala v2.12.0

### ISSUE THREAD

**Issue by marconilanna** [pathikrit/better-files#90]
The [Scala 2.12.0 release train](https://github.com/scala/make-release-notes/blob/2.12.x/projects-2.12.md) is here. Please publish for 2.12.0 and [submit a pull request](https://github.com/scala/make-release-notes/edit/2.12.x/projects-2.12.md) to let the world know what libraries are available.

**Comment by xavier-fernandez** [comment]
+1

**Comment by noam-almog** [comment]
I created a PR for this #86, waiting for merge for quite a while now

**Comment by romainreuillon** [comment]
Any news here?

**Comment by pathikrit** [comment]
@noam-almog : Hi, I am not that familiar with Github. I don't want to merge your PR into master yet but into a separate 2.12 branch. How can I do that?

**Comment by noam-almog** [comment]
I guess you can check it out from my fork: https://github.com/noam-almog/better-files/branches

**Comment by jotomo** [comment]
@pathikrit Alternatively, you can create a _2.12_ branch in this repo, @noam-almog can change the target branch of the PR to it, and then you can merge the PR into the newly created _2.12_.

**Comment by antonkulaga** [comment]
+1
I am already using Scala 2.12.1 in a new project and I miss better-files there

**Comment by mslinn** [comment]
+1

**Comment by sfxcode** [comment]
+1

**Comment by philwalk** [comment]
+1

**Comment by alex3kov** [comment]
+1

**Comment by pathikrit** [comment]
better-files 2.12 is on Maven: https://oss.sonatype.org/content/repositories/releases/com/github/pathikrit/
