### ISSUE TITLE
Implement file diff

### ISSUE THREAD

**Issue by wsargent** [pathikrit/better-files#91]
The file system operations at https://github.com/pathikrit/better-files#file-system-operations specifies 

"Utilities to ls, cp, rm, mv, ln, md5, diff, touch, cat etc:"

but there is no "diff" equivalent in the list:

```
file.touch()
file.delete()     // unlike the Java API, also works on directories as expected (deletes children recursively)
file.clear()      // If directory, deletes all children; if file clears contents
file.renameTo(newName: String)
file.moveTo(destination)
file.copyTo(destination)       // unlike the default API, also works on directories (copies recursively)
file.linkTo(destination)                     // ln file destination
file.symbolicLinkTo(destination)             // ln -s file destination
file.{checksum, md5, sha1, sha256, sha512, digest}   // also works for directories
file.setOwner(user: String)      // chown user file
file.setGroup(group: String)     // chgrp group file
Seq(file1, file2) `>:` file3     // same as cat file1 file2 > file3
Seq(file1, file2) >>: file3      // same as cat file1 file2 >> file3
file.isReadLocked / file.isWriteLocked / file.isLocked
File.newTemporaryDirectory() / File.newTemporaryFile() // create temp dir/file
```

**Comment by pathikrit** [comment]
What do you expect the return type of a `diff(file1, file2)` to return?

**Comment by jvican** [comment]
@wsargent Any ideas on this? Diff files can be implemented in different ways. Will you expect the return type to be a string with the usual patch format?
  
This is a nice to have feature. I wouldn't say it's very important though, developers in need of this usually end up using https://code.google.com/p/google-diff-match-patch/ which is very robust. We could perhaps use it for the underlying implementation.

**Comment by wsargent** [comment]
Maybe this is a bit unclear -- I don't actually need there to be a diff() feature.  I just want the text to match the actual list of utilities.  If you can fix that line, that's all I'm looking for.

**Comment by pathikrit** [comment]
@wsargent : Yes, I changed the issue from removing diff from the README (which we should do for now) to actually implement file diff. I think what @jvican suggested makes sense - to output a patch format.

**Comment by pathikrit** [comment]
@jvican : Actually I don't know if a String patch is enough. I would prefer an ADT like this

```scala
sealed trait Diff
object Diff {
  case class Added(line: String) extends Diff
  case object Deleted extends Diff
  case class Modified(from: String, to: String) extends Diff
}


def diff(file1: File, file: File): Seq[(Int, Diff)]
```

**Comment by wsargent** [comment]
Well, it still says "diff" right now:

https://github.com/pathikrit/better-files#file-system-operations

**Comment by pathikrit** [comment]
@wsargent : And, that's why this issue is still open.

**Comment by jvican** [comment]
That ADT looks fine. The only issue would be to parse the diff files produced by things like https://code.google.com/p/google-diff-match-patch/. I wouldn't be surprised if someone has already done so.
  
This looks like the perfect ticket to hack on in several hackathons. Otherwise, someone from the Community could help us and contribute it.

**Comment by pathikrit** [comment]
Closing this as out of scope of this library
